[Feat/101] 게시판 게시물 등록 API 구현
Gamegoo-repo/Gamegoo-Server-v2 pull request #110
Opened 2024-12-29 06:56 UTC by coldmans

# 🚀 개요

>게시판 게시물 등록  API 구현 

## ⏳ 작업 상세 내용

- [ ] 게시판 관련 DTO 생성
- [ ] 등록 API 엔드포인트 생성
- [ ] Service 계층 로직 작성

## 📝 더 꼼꼼히 봐야할 부분

validation 로직에 주포지션과 부포지션이 동일한 경우 에러를 생성하는 코드를 구현했는데 이 부분에 대한 생각

- [ ] 없을 경우 체크

## 🔍 반드시 참고해야하는 변경 사항

- [ ] 없을 경우 체크

2024-12-29 08:14 UTC, Eunjin3395 requested changes
전반적으로 저희 다른 v2 코드들과 비슷한 구조를 갖도록 수정 작업이 필요할 것 같습니다 !
고생하셨습니다!!

2024-12-29 08:14 UTC, Eunjin3395 commented on src/main/java/com/gamegoo/gamegoo_v2/content/board/dto/request/BoardRequest.java
> +    public static class boardInsertDTO {
dto 네이밍도 저희 컨벤션에 맞게 수정 부탁드립니다.

2024-12-29 08:14 UTC, Eunjin3395 commented on src/main/java/com/gamegoo/gamegoo_v2/content/board/dto/request/BoardRequest.java
> +        List<Long> gameStyles;
이 list에 대한 notnull 검증이 없어서 gameStyles 필드를 누락했을 경우 internal server error 발생합니다..!

2024-12-29 08:14 UTC, Eunjin3395 commented on src/main/java/com/gamegoo/gamegoo_v2/content/board/service/BoardService.java
> +    private final MemberService memberService;
memberService 의존하지 않도록 제거 부탁드립니다..!

2024-12-29 08:14 UTC, Eunjin3395 commented on src/main/java/com/gamegoo/gamegoo_v2/content/board/service/BoardService.java
> +    private final BoardGameStyleRepository boardGameStyleRepository;
boardGameStyleRepository를 현재 사용하고 있지 않은데 이 부분 추가하신 이유가 있으신가요?!

2024-12-29 10:33 UTC, rimi3226 requested changes

2024-12-29 10:33 UTC, rimi3226 commented on src/main/java/com/gamegoo/gamegoo_v2/content/board/controller/BoardController.java
> +            @AuthMember Member member,                              // ← @AuthMember 사용
매개변수에 주석은 지우는 편이 더 좋을 것 같습니다.

2024-12-29 10:33 UTC, rimi3226 commented on src/main/java/com/gamegoo/gamegoo_v2/content/board/dto/request/BoardRequest.java
> +public class BoardRequest {
저희 v1 레포에서는 하나의 dto class에서 여러개 클래스를 만들어서 관리했었는데, 이제는 각 dto마다 별도로 클래스를 만들어서 사용하고 있습니다. 
다른 dto 참고하셔서 BoardUpdateRequest BoardCreateRequest 와 같이 나누는게 좋을 것 같습니다. 
클래스 안에 클래스가 있는 형태가 아니다보니, @Getter와 @Builder를 클래스 안에 넣지 말고 밖에 넣는 것이 좋을 것 같습니다.
dto 예시입니다.
```
@Builder
@Getter
public class IsMikeRequest {

    @NotNull(message = "isMike 값은 비워둘 수 없습니다.")
    Boolean isMike;

}
```

2024-12-29 10:33 UTC, rimi3226 commented on src/main/java/com/gamegoo/gamegoo_v2/content/board/dto/response/BoardResponse.java
> +public class BoardResponse {
resposne도 마찬가지로 현재 각 controller에 응답하는 dto마다 새로운 클래스로 만들어서 구현하고있습니다.
게시판은 내 프로필 조회 dto 참고하시면 편할 것 같아서 첨부합니다.
```
@Getter
@Builder
public class MyProfileResponse {

    Long id;
    Integer profileImg;
    Boolean mike;
    String email;
    String gameName;
    String tag;
    Tier tier;
    Integer gameRank;
    Double mannerRank;
    Integer mannerLevel;
    String updatedAt;
    Integer mainP;
    Integer subP;
    Integer wantP;
    Boolean isAgree;
    Boolean isBlind;
    String loginType;
    Double winrate;
    List<GameStyleResponse> gameStyleResponseList;
    List<ChampionResponse> championResponseList;

    public static MyProfileResponse of(Member member, Double mannerRank) {
        List<GameStyleResponse> gameStyleResponseList = member.getMemberGameStyleList().stream()
                .map(memberGameStyle -> GameStyleResponse.of(memberGameStyle.getGameStyle()))
                .toList();

        List<ChampionResponse> championResponseList = member.getMemberChampionList().stream()
                .map(memberChampion -> ChampionResponse.of(memberChampion.getChampion()))
                .toList();

        return MyProfileResponse.builder()
                .id(member.getId())
                .mike(member.isMike())
                .email(member.getEmail())
                .gameName(member.getGameName())
                .tag(member.getTag())
                .tier(member.getTier())
                .gameRank(member.getGameRank())
                .profileImg(member.getProfileImage())
                .mannerLevel(member.getMannerLevel())
                .mannerRank(mannerRank)
                .mainP(member.getMainPosition())
                .subP(member.getSubPosition())
                .wantP(member.getWantPosition())
                .isAgree(member.isAgree())
                .isBlind(member.isBlind())
                .winrate(member.getWinRate())
                .loginType(String.valueOf(member.getLoginType()))
                .updatedAt(String.valueOf(member.getUpdatedAt()))
                .gameStyleResponseList(gameStyleResponseList)
                .championResponseList(championResponseList)
                .build();
    }

}
```

2024-12-29 10:33 UTC, rimi3226 commented on src/main/java/com/gamegoo/gamegoo_v2/content/board/service/BoardService.java
> +    @Transactional
Service는 각 구현 기능의 세부적인 기능을 하도록 구현해주세요! 최대한 하나의 함수에 하나의 기능만 하도록 구현해주시면 될 것 같습니다.
FacadeService에서 Service단에서 만든 코드를 조합해서 만든다고 생각하시면 편할 것 같습니다.

2024-12-29 10:33 UTC, rimi3226 commented on src/main/java/com/gamegoo/gamegoo_v2/content/board/service/BoardService.java
> +            throw new BoardException(ErrorCode.BOARD_WANT_POSITION_BAD_REQUEST);
@Min, @Max, @NotNull 어노테이션을 dto에 붙일 경우 해당 검증을 Service단에서 안할 수 있습니다.

2024-12-29 10:33 UTC, rimi3226 commented on src/main/java/com/gamegoo/gamegoo_v2/content/board/service/BoardService.java
> +    }
@Min @Max 어노테이션을 Dto에 붙이는 편이 더 좋을 것 같습니다.
다음은 포지션 수정 dto 예시입니다.
```
@Getter
@Builder
public class PositionRequest {

    @Min(value = 0, message = "메인 포지션의 값은 0이상이어야 합니다.")
    @Max(value = 5, message = "메인 포지션의 값은 5이하이어야 합니다.")
    int mainP;
    
    @Min(value = 0, message = "서브 포지션의 값은 0이상이어야 합니다.")
    @Max(value = 5, message = "서브 포지션의 값은 5이하이어야합니다.")
    int subP;

    @Min(value = 0, message = "원하는 포지션의 값은 0이상이어야 합니다.")
    @Max(value = 5, message = "원하는 포지션의 값은 5이하이어야합니다.")
    int wantP;

}

```

2024-12-29 10:33 UTC, rimi3226 commented on src/main/java/com/gamegoo/gamegoo_v2/content/board/service/BoardService.java
> +    }
응답 dto를 생성해서 return하는 부분은 facadeService에서 해주시면 좋을 것 같습니다.

2024-12-29 10:33 UTC, rimi3226 commented on src/main/java/com/gamegoo/gamegoo_v2/core/exception/common/ErrorCode.java
>      BOARD_WANT_POSITION_BAD_REQUEST(BAD_REQUEST, "BOARD_409", "상대포지션 값은 0~5만 가능합니다."),
DTO에 Valid 어노테이션을 붙일 경우 해당 에러코드는 필요 없을 것 같습니다.

2024-12-29 10:35 UTC, rimi3226 commented
PR 올리실 때 다음과 같이 수정해주시면 좋을 것 같습니다! 

### AS-IS 

validation 로직에 주포지션과 부포지션이 동일한 경우 에러를 생성하는 코드를 구현했는데 이 부분에 대한 생각

- [ ] 없을 경우 체크

### TO-BE
- [ ] validation 로직에 주포지션과 부포지션이 동일한 경우 에러를 생성하는 코드를 구현했는데 이 부분에 대해서 어떻게 생각하시는지 궁금합니다.

2024-12-29 11:03 UTC, coldmans commented on src/main/java/com/gamegoo/gamegoo_v2/content/board/dto/response/BoardResponse.java
> +    @NoArgsConstructor
유연성 측면에서 기본생성자 생성 어노테이션을 넣어뒀습니다. 하지만 Response dto니까 빼도 될것같습니다.

2024-12-29 11:08 UTC, coldmans commented on src/main/java/com/gamegoo/gamegoo_v2/content/board/dto/request/BoardRequest.java
> +    @Setter
현재 로직에서는 @Setter가 필요하지 않지만 추후 테스트 환경에서 특정 필드만 변경해 테스트를 진행하거나, 요청 객체를 동적으로 수정해야 할 상황을 대비해 넣었습니다. 하지만 당장의 필요성이 없으므로 제거하도록 하겠습니다

2024-12-29 14:16 UTC, rimi3226 commented on src/main/java/com/gamegoo/gamegoo_v2/content/board/service/BoardCreateService.java
클래스 이름을 BoardCreateService로 하셨는데 해당 서비스에서 게시판 조회도 함께 하고 있으니 
BoardService로 하는건 어떠신가요..?! BoardService에 crud에 필요한 메서드들을 포함시키면 좋을 것 같습니다!

2024-12-29 14:16 UTC, rimi3226 commented on src/main/java/com/gamegoo/gamegoo_v2/content/board/service/BoardCreateService.java
> +    @Transactional
혹시 여기도 문서 주석 달아주실 수 있으신가요?

2024-12-29 14:16 UTC, rimi3226 approved these changes

2024-12-29 14:16 UTC, rimi3226 approved these changes

2024-12-29 14:17 UTC, Eunjin3395 approved these changes
고생하셨습니다!!

2024-12-29 14:17 UTC, Eunjin3395 commented on src/main/java/com/gamegoo/gamegoo_v2/content/board/controller/BoardController.java
> +            @RequestBody BoardInsertRequest request) {
여기 request dto에 @Valid도 붙여주셔야 dto에 어노테이션들이 작동합니다!

2024-12-29 14:17 UTC, Eunjin3395 commented on src/main/java/com/gamegoo/gamegoo_v2/content/board/service/BoardCreateService.java
저희 서비스는 BoardService로 하는거 어떠신가요?!

2024-12-29 14:17 UTC, Eunjin3395 commented on src/main/java/com/gamegoo/gamegoo_v2/content/board/dto/response/BoardInsertResponse.java
> +    private Boolean mike;
여기서 null일 수 없는 것들은 원시타입(int, boolean)으로 쓰는거 어떠신가요?!

2024-12-29 14:17 UTC, Eunjin3395 commented on src/main/java/com/gamegoo/gamegoo_v2/content/board/service/BoardCreateService.java
> +    }
제 생각엔 create랑 save는 한 메소드에서 해도 괜찮을 것 같아요..!

2024-12-30 07:12 UTC, rimi3226 approved these changes
고생하셨습니다!

2024-12-30 07:12 UTC, rimi3226 commented on src/main/java/com/gamegoo/gamegoo_v2/content/board/domain/BoardGameStyle.java
> +    @Setter
@Setter 어노테이션의 경우, 저희 프로젝트에서 최대한 지양하고있습니다. 왜냐하면 불변성을 침해할 수 있기 때문입니다. 
그래서 저희는 updateBoard와 같은 메소드를 직접 만들어서 호출하는 방식으로 구현하고 있습니다.
혹시 이 부분 수정해주실 수 있으신가요?
다른 의견 있으시면 편하게 말씀해주세요!!

2024-12-30 07:12 UTC, rimi3226 commented on src/main/java/com/gamegoo/gamegoo_v2/content/board/domain/Board.java
> +        boardGameStyle.setBoard(this);
제가 구현한 MemberGameStyle의 경우 다음과 같습니다.
```
public void setMember(Member member) {
    if (this.member != null) {
        this.member.getMemberGameStyleList().remove(this);
    }
    this.member = member;
    member.getMemberGameStyleList().add(this);
}
```

회원이 선택한 게임스타일을 저장하는 MemberGameStyle 엔티티에 작성된 메소드입니다. 
이 방식을 사용하면 @Setter를 사용하지 않아도 구현이 가능합니다.

다만, setMember 메소드를 직접 만들어서 구현하나, lombok의 @Setter를 사용하는거나 setMember가 public이기 때문에 비슷해보일 수도 있다는 생각이 드네요.
@Eunjin3395 은진님은 이 부분 어떻게 생각하시나요?

2024-12-30 07:12 UTC, rimi3226 commented on src/main/java/com/gamegoo/gamegoo_v2/content/board/controller/BoardController.java
> +        return ApiResponse.ok(responseDTO);
이 부분을 
```
return ApiResponse.ok(boardFacadeService.createBoard(request, member)); 
``` 
이렇게 변경할 수도 있습니당..!

2024-12-30 12:25 UTC, Eunjin3395 reviewed
BoardGameStyleService에서 findGameStyle 메소드가 던지고 있는 에러가 잘못된 것 같습니다..! gamestyleId로 0이나 -1 등의 값을 넣으면 해당 게임스타일이 존재하지 않는다는 내용의 에러가 나오는게 맞아보이는데, 지금은 게임 스타일 최대 개수를 초과했다는 에러가 나오고 있습니다!

2024-12-30 12:28 UTC, Eunjin3395 commented on src/main/java/com/gamegoo/gamegoo_v2/content/board/domain/Board.java
> +        boardGameStyle.setBoard(this);
저는 효림님 방식대로 setter를 직접 구현하고 그 안에서 연관관계 매핑까지 해주는게 좋은 것 같습니다..! 롬복으로 생성된 setter나 직접 구현한 setMember나 둘다 퍼블릭이긴한데 직접 구현한 경우에는 board <-> boardGameStyle 간 연관관계까지 지정해줄 수 있을 것 같아서요..! 지금은 board 엔티티에서 gameStyle을 매핑하게 되어있는데 이걸 boardGameStyle 엔티티에서 매핑하도록 수정하면 좋을 것 같습니다!

2024-12-30 12:34 UTC, Eunjin3395 requested changes

2024-12-30 12:34 UTC, Eunjin3395 commented on src/main/java/com/gamegoo/gamegoo_v2/content/board/dto/request/BoardInsertRequest.java
제가 말씀드렸던 원시 타입 사용은 request dto가 아니라 response dto에서 원시타입 사용하는거였습니다...!
request dto에서는 이렇게 null을 담을 수 없는 타입으로 선언하면 아예 @NotNull 검증이 안되는 것 같아요..! 올려주신 코드로 테스트해보면 mainPosition을 json에 넣지 않고 요청해도 자동으로 0으로 값이 들어가면서 게시글 등록이 성공해버립니다..!

2024-12-30 14:48 UTC, Eunjin3395 approved these changes
고생많으셨습니다 👍

2024-12-31 05:46 UTC, merged