[Feat/53] Riot 계정 존재하는지 검증하는 API
Gamegoo-repo/Gamegoo-Server-v2 pull request #62
Opened 2024-12-20 00:06 UTC by rimi3226

# 🚀 개요

> Riot 계정 존재하는지 검증하는 API

## ⏳ 작업 상세 내용

- [ ] RestTemplate 사용 가능하도록 AppConfig 설정
- [ ] RiotService 역할에 따라 분할
- [ ] riot verify API 구현
- [ ] Interceptor verify riot API jwt 검증 안하도록 설정
- [ ] RiotException 추가

## 📝 더 꼼꼼히 봐야할 부분

- [ ] RiotService를 각 용도에 따라 Account, Info, Record로 나눴는데 이렇게 나누는 방식이 괜찮은지 궁금합니다. Account : 계정 검증용, Record : 사용자 매칭 기록에서 가져오는 정보(최근 매칭에서 가장 많이 사용한 챔피언 3가지 들고오기), Info : 티어, 승률과 같이 소환사의 정보

## 🔍 반드시 참고해야하는 변경 사항

- [ ] RIOT_API 환경변수 설정

2024-12-20 01:17 UTC, Eunjin3395 requested changes
고생하셨습니다 ㅠㅠ

저라면 Riot 서비스 account, info, record 각각 안나누고 그냥 RiotService 안에서 다 할 것 같아요 !

2024-12-20 01:17 UTC, Eunjin3395 commented on .github/workflows/github_actions.yml
이거 환경변수 추가할 때 여기뿐만 아니라
6. Docker 이미지 생성 및 Push << 이쪽 부분에 build-args 에도 추가,
7. EC2에 SSH로 접속하여 Docker 컨테이너 실행 << 여기 script에도 추가, 

그리고 Dockerfile에
GitHub Actions에서 전달된 빌드 변수들을 ARG로 정의
아래에도 ARG 추가해주셔야 할 것 같아요 !

2024-12-20 01:17 UTC, Eunjin3395 commented on src/main/java/com/gamegoo/gamegoo_v2/auth/dto/JoinRequest.java
> +    String email;
여기 각 필드 끝날 때마다 한칸씩 엔터 넣어주는 거 어떠신가요?!

2024-12-20 01:17 UTC, Eunjin3395 commented on src/main/java/com/gamegoo/gamegoo_v2/exception/common/ErrorCode.java
> +    RIOT_NOT_FOUND(HttpStatus.NOT_FOUND, "RIOT404", "해당 Riot 계정이 존재하지 않습니다."),
여기 코드마다 문자랑 숫자 사이에 _ 넣어주세요!

2024-12-20 01:17 UTC, Eunjin3395 commented on src/main/java/com/gamegoo/gamegoo_v2/riot/controller/RiotController.java
> +@Slf4j
지금 특별히 로그 찍는 코드가 없어서 이 어노테이션은 빼도 될 것 같습니다!

2024-12-20 01:17 UTC, Eunjin3395 commented on src/main/java/com/gamegoo/gamegoo_v2/riot/dto/RiotVerifyExistUserRequest.java
> +    String gameName;
여기도 엔터로 구분하면 더 좋을 것 같아요!

2024-12-20 01:17 UTC, Eunjin3395 commented on src/main/java/com/gamegoo/gamegoo_v2/riot/service/RiotFacadeService.java
> +        }
그런데 riotAccountService.getPuuid에서 이미 
```
RiotAccountResponse response = restTemplate.getForObject(url, RiotAccountResponse.class);

            if (response == null) {
                throw new RiotException(ErrorCode.RIOT_NOT_FOUND);
            }

            return response.getPuuid();
```
이걸 하고 있는데 여기서도 이 검증이 필요한건가요?!
만약 response는 null이 아니지만 response.getPuuid()는 null일 수 있는거라면 아예 puuid null 검증도 riotAccountService 안에서 하는 것도 괜찮을 것 같아요!

2024-12-20 01:17 UTC, Eunjin3395 commented on src/main/java/com/gamegoo/gamegoo_v2/riot/service/RiotFacadeService.java
> +        }
이부분도 마찬가지로 필요하다면 riotAccountService 안에서 하는게 좋을 것 같습니다..!

2024-12-20 01:18 UTC, Eunjin3395 commented
그리고 RIOT_API 이거 환경변수 저희 노션에 v2 환경변수 페이지에도 추가해주시면 좋을 것 같습니다 !!

2024-12-20 01:23 UTC, rimi3226 commented
> 고생하셨습니다 ㅠㅠ
> 
> 저라면 Riot 서비스 account, info, record 각각 안나누고 그냥 RiotService 안에서 다 할 것 같아요 !

Riot 서비스가 지금은 puuid 가져오기, summonerid 가져오기, tier winrate rank 가져오기, 최근 매칭 아이디 여러개 가져오기, 각 매칭 정보로 챔피언 데이터 조회하기가 있어요! 근데 이제 전적 가져오고 지난 티어도 반영하게되면 훨씬 더 많아질 것 같아서 나눴습니다..! 그래도 혹시 Service 하나에서 하는게 편할까요?

2024-12-20 01:28 UTC, Eunjin3395 commented
아하,, 뭔가 추가되어야할게 많은거라면 저는 나눠도 좋을 것 같아요 !! 그럼 혹시 account는 명칭을 auth 로 바꾸는건 어떠세요? RiotAuthService 이런식으로요,, 뭔가 세 단어가 의미가 다 비슷한 것 같아서 약간 헷갈리는 감이 있는 것 같아요

2024-12-22 09:37 UTC, rimi3226 commented on .github/workflows/github_actions.yml
넵!

2024-12-22 09:38 UTC, rimi3226 commented on src/main/java/com/gamegoo/gamegoo_v2/auth/dto/JoinRequest.java
> +    String email;
넵!

2024-12-22 09:48 UTC, merged